"""rename address

Revision ID: 75aca1c54988
Revises: 1b06c7eae2aa
Create Date: 2024-04-12 01:37:48.121133

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75aca1c54988'
down_revision = '1b06c7eae2aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('departments', sa.Column('location', sa.String(), nullable=True))
    op.drop_column('departments', 'address')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('departments', sa.Column('address', sa.VARCHAR(), nullable=True))
    op.drop_column('departments', 'location')
    # ### end Alembic commands ###
